// Package fonts writes a CSS file whose @font-face rules carry the fonts as
// base64 data: URIs, so a page renders the same opened from the filesystem,
// on any machine, with no network: Safari refuses file:// sibling
// subresources, and a data: URI has no origin to refuse. font-display is
// block by default, so a render never captures a fallback face.
package fonts

import (
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"unicode"

	"github.com/lockyc/imgkit/internal/cli"
	"github.com/lockyc/imgkit/internal/engine"
)

// displays are the font-display values CSS defines.
var displays = []string{"auto", "block", "swap", "fallback", "optional"}

const usage = "fonts [--display block] -o fonts.css FILE:FAMILY:WEIGHT:STYLE..."

var formats = map[string][2]string{
	".woff2": {"font/woff2", "woff2"},
	".woff":  {"font/woff", "woff"},
	".ttf":   {"font/ttf", "truetype"},
	".otf":   {"font/otf", "opentype"},
}

type face struct{ file, family, weight, style string }

// parseFace splits FILE:FAMILY:WEIGHT:STYLE from the right, so a colon in
// the file path survives.
func parseFace(s string) (face, error) {
	parts := strings.Split(s, ":")
	n := len(parts)
	if n < 4 {
		return face{}, fmt.Errorf("%q: want FILE:FAMILY:WEIGHT:STYLE", s)
	}
	f := face{file: strings.Join(parts[:n-3], ":"), family: parts[n-3], weight: parts[n-2], style: parts[n-1]}
	if f.family == "" || strings.ContainsAny(f.family, `"\`) || strings.IndexFunc(f.family, unicode.IsControl) >= 0 {
		return face{}, fmt.Errorf("%q: family must be non-empty, without quotes, backslashes or control characters", s)
	}
	if w, err := strconv.Atoi(f.weight); (err != nil || w < 1 || w > 1000) && f.weight != "normal" && f.weight != "bold" {
		return face{}, fmt.Errorf("%q: weight must be 1-1000, normal or bold", s)
	}
	if f.style != "normal" && f.style != "italic" && f.style != "oblique" {
		return face{}, fmt.Errorf("%q: style must be normal, italic or oblique", s)
	}
	if _, ok := formats[strings.ToLower(filepath.Ext(f.file))]; !ok {
		return face{}, fmt.Errorf("%q: %s is not a web font; use .woff2, .woff, .ttf or .otf", s, filepath.Ext(f.file))
	}
	return f, nil
}

// Main runs `imgkit fonts`.
func Main(ctx context.Context, args []string, stdout, stderr io.Writer) int {
	fs := cli.Flags("fonts", usage, stderr)
	out := fs.String("o", "", "the CSS file to write (required)")
	display := fs.String("display", "block", "font-display value")
	rest, code, ok := cli.Parse(fs, args, -1)
	if !ok {
		return code
	}
	usageErr := func(err error) int { return cli.Usage(stderr, "fonts", "%v", err) }
	if *out == "" || len(rest) == 0 {
		return usageErr(fmt.Errorf("give -o and at least one FILE:FAMILY:WEIGHT:STYLE"))
	}
	if !slices.Contains(displays, *display) {
		return usageErr(fmt.Errorf("--display %q: use %s", *display, strings.Join(displays, ", ")))
	}
	var faces []face
	for _, s := range rest {
		f, err := parseFace(s)
		if err != nil {
			return usageErr(err)
		}
		faces = append(faces, f)
	}

	// Check that -o is not the same file as any input font
	for _, f := range faces {
		if engine.SameFile(*out, f.file) {
			return usageErr(fmt.Errorf("-o is the same file as a font input: %q", f.file))
		}
	}

	var b strings.Builder
	b.WriteString("/* Generated by imgkit fonts. Regenerate it rather than editing it. */\n\n")
	for _, f := range faces {
		data, err := os.ReadFile(f.file)
		if err != nil {
			return cli.Fail(stderr, "fonts", err)
		}
		fm := formats[strings.ToLower(filepath.Ext(f.file))]
		fmt.Fprintf(&b, "@font-face {\n  font-family: %q;\n  font-style: %s;\n  font-weight: %s;\n  font-display: %s;\n  src: url(data:%s;base64,%s) format(%q);\n}\n",
			f.family, f.style, f.weight, *display, fm[0], base64.StdEncoding.EncodeToString(data), fm[1])
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		return cli.Fail(stderr, "fonts", err)
	}
	fmt.Fprintf(stdout, "wrote %s (%d faces, %d bytes)\n", *out, len(faces), b.Len())
	return 0
}
