package fonts

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestFonts(t *testing.T) {
	dir := t.TempDir()
	font := filepath.Join(dir, "Face:Odd.woff2")
	os.WriteFile(font, []byte("wOF2abc"), 0o644)
	out := filepath.Join(dir, "fonts.css")
	var o, e bytes.Buffer
	code := Main(context.Background(), []string{"-o", out, font + ":Londrina Solid:900:normal", font + ":Bangers:400:italic"}, &o, &e)
	if code != 0 {
		t.Fatalf("code %d: %s", code, e.String())
	}
	b, _ := os.ReadFile(out)
	want := `/* Generated by imgkit fonts. Regenerate it rather than editing it. */

@font-face {
  font-family: "Londrina Solid";
  font-style: normal;
  font-weight: 900;
  font-display: block;
  src: url(data:font/woff2;base64,d09GMmFiYw==) format("woff2");
}
@font-face {
  font-family: "Bangers";
  font-style: italic;
  font-weight: 400;
  font-display: block;
  src: url(data:font/woff2;base64,d09GMmFiYw==) format("woff2");
}
`
	if string(b) != want {
		t.Errorf("css:\n%s\nwant:\n%s", b, want)
	}
}

func TestFontsRejects(t *testing.T) {
	dir := t.TempDir()
	ttf := filepath.Join(dir, "a.ttf")
	os.WriteFile(ttf, []byte("x"), 0o644)
	out := filepath.Join(dir, "o.css")
	cases := []struct {
		args []string
		code int
		want string
	}{
		{[]string{"-o", out, ttf + ":A:400"}, 2, "FILE:FAMILY:WEIGHT:STYLE"},
		{[]string{"-o", out, ttf + ":A:heavy:normal"}, 2, "weight"},
		{[]string{"-o", out, ttf + ":A:400:slanted"}, 2, "style"},
		{[]string{"-o", out, ttf + `:A"B:400:normal`}, 2, "family"},
		{[]string{"-o", out, filepath.Join(dir, "a.eot") + ":A:400:normal"}, 2, ".eot"},
		{[]string{"-o", out, filepath.Join(dir, "missing.woff2") + ":A:400:normal"}, 1, "missing.woff2"},
		{[]string{"-o", out, ttf + ":A\nB:400:normal"}, 2, "family"},
		{[]string{"-o", out, ttf + ":A\x7fB:400:normal"}, 2, "family"},
		{[]string{"--display", "block;}", "-o", out, ttf + ":A:400:normal"}, 2, "--display"},
		{[]string{ttf + ":A:400:normal"}, 2, "-o"},
		{[]string{"-o", ttf, ttf + ":A:400:normal"}, 2, "same file"},
	}
	for _, c := range cases {
		var o, e bytes.Buffer
		if code := Main(context.Background(), c.args, &o, &e); code != c.code || !strings.Contains(e.String(), c.want) {
			t.Errorf("%q: code %d stderr %q; want %d containing %q", c.args, code, e.String(), c.code, c.want)
		}
	}
	if _, err := os.Stat(out); err == nil {
		t.Error("a failed run wrote the CSS")
	}
}

func TestFontsSameFileAsOutput(t *testing.T) {
	dir := t.TempDir()
	font := filepath.Join(dir, "test.woff2")
	os.WriteFile(font, []byte("wOF2abc"), 0o644)
	var o, e bytes.Buffer
	code := Main(context.Background(), []string{"-o", font, font + ":Test:400:normal"}, &o, &e)
	if code != 2 {
		t.Errorf("code %d, want 2; stderr: %s", code, e.String())
	}
	if !strings.Contains(e.String(), "same file") {
		t.Errorf("stderr %q should contain 'same file'", e.String())
	}
	// Verify the file still exists (wasn't deleted by partial execution)
	if _, err := os.Stat(font); err != nil {
		t.Error("font file was deleted after error")
	}
}
