// Package fonts writes a CSS file whose @font-face rules carry the fonts as
// base64 data: URIs, so a page renders the same opened from the filesystem,
// on any machine, with no network: Safari refuses file:// sibling
// subresources, and a data: URI has no origin to refuse. font-display is
// block by default, so a render never captures a fallback face. --subset
// cuts each font to a named set of characters with hb-subset first, so the
// CSS carries only the glyphs the page's language uses.
package fonts

import (
	"context"
	"encoding/base64"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"unicode"

	"github.com/lockyc/plate/internal/cli"
	"github.com/lockyc/plate/internal/engine"
)

// displays are the font-display values CSS defines.
var displays = []string{"auto", "block", "swap", "fallback", "optional"}

const usage = "fonts [--display block] [--subset latin] -o fonts.css FILE:FAMILY:WEIGHT:STYLE..."

// subsets are the named character sets --subset takes, as hb-subset
// --unicodes ranges. latin is Basic Latin, Latin-1 Supplement and the
// General Punctuation English text uses (dashes, quotes, ellipsis, primes,
// guillemets), plus the euro sign.
var subsets = map[string]string{
	"latin": "20-7E,A0-FF,2010-2027,2030-203A,20AC",
}

var formats = map[string][2]string{
	".woff2": {"font/woff2", "woff2"},
	".woff":  {"font/woff", "woff"},
	".ttf":   {"font/ttf", "truetype"},
	".otf":   {"font/otf", "opentype"},
}

type face struct{ file, family, weight, style string }

// parseFace splits FILE:FAMILY:WEIGHT:STYLE from the right, so a colon in
// the file path survives.
func parseFace(s string) (face, error) {
	parts := strings.Split(s, ":")
	n := len(parts)
	if n < 4 {
		return face{}, fmt.Errorf("%q: want FILE:FAMILY:WEIGHT:STYLE", s)
	}
	f := face{file: strings.Join(parts[:n-3], ":"), family: parts[n-3], weight: parts[n-2], style: parts[n-1]}
	if f.family == "" || strings.ContainsAny(f.family, `"\`) || strings.IndexFunc(f.family, unicode.IsControl) >= 0 {
		return face{}, fmt.Errorf("%q: family must be non-empty, without quotes, backslashes or control characters", s)
	}
	if w, err := strconv.Atoi(f.weight); (err != nil || w < 1 || w > 1000) && f.weight != "normal" && f.weight != "bold" {
		return face{}, fmt.Errorf("%q: weight must be 1-1000, normal or bold", s)
	}
	if f.style != "normal" && f.style != "italic" && f.style != "oblique" {
		return face{}, fmt.Errorf("%q: style must be normal, italic or oblique", s)
	}
	if _, ok := formats[strings.ToLower(filepath.Ext(f.file))]; !ok {
		return face{}, fmt.Errorf("%q: %s is not a web font; use .woff2, .woff, .ttf or .otf", s, filepath.Ext(f.file))
	}
	return f, nil
}

// Main runs `plate fonts`.
func Main(ctx context.Context, args []string, stdout, stderr io.Writer) int {
	fs := cli.Flags("fonts", usage, stderr)
	out := fs.String("o", "", "the CSS file to write (required)")
	display := fs.String("display", "block", "font-display value")
	subset := fs.String("subset", "", "cut each font to a named character set before embedding: latin (needs .ttf or .otf input)")
	rest, code, ok := cli.Parse(fs, args, -1)
	if !ok {
		return code
	}
	usageErr := func(err error) int { return cli.Usage(stderr, "fonts", "%v", err) }
	if *out == "" || len(rest) == 0 {
		return usageErr(fmt.Errorf("give -o and at least one FILE:FAMILY:WEIGHT:STYLE"))
	}
	if !slices.Contains(displays, *display) {
		return usageErr(fmt.Errorf("--display %q: use %s", *display, strings.Join(displays, ", ")))
	}
	unicodes, subsetting := subsets[*subset]
	given := false
	fs.Visit(func(f *flag.Flag) { given = given || f.Name == "subset" })
	if given && !subsetting {
		return usageErr(fmt.Errorf("--subset %q: use latin", *subset))
	}
	var faces []face
	for _, s := range rest {
		f, err := parseFace(s)
		if err != nil {
			return usageErr(err)
		}
		if ext := strings.ToLower(filepath.Ext(f.file)); subsetting && ext != ".ttf" && ext != ".otf" {
			return usageErr(fmt.Errorf("%q: --subset needs .ttf or .otf input; hb-subset cannot read %s", s, ext))
		}
		faces = append(faces, f)
	}

	// Check that -o is not the same file as any input font
	for _, f := range faces {
		if engine.SameFile(*out, f.file) {
			return usageErr(fmt.Errorf("-o is the same file as a font input: %q", f.file))
		}
	}
	// A failure below must not leave an earlier run's CSS looking current.
	if err := os.Remove(*out); err != nil && !errors.Is(err, os.ErrNotExist) {
		return cli.Fail(stderr, "fonts", err)
	}

	var b strings.Builder
	b.WriteString("/* Generated by plate fonts. Regenerate it rather than editing it. */\n\n")
	var tmp string
	if subsetting {
		d, err := os.MkdirTemp("", "plate-fonts-")
		if err != nil {
			return cli.Fail(stderr, "fonts", err)
		}
		defer os.RemoveAll(d)
		tmp = d
	}
	for i, f := range faces {
		src := f.file
		if subsetting {
			src = filepath.Join(tmp, strconv.Itoa(i)+filepath.Ext(f.file))
			if _, err := engine.Run(ctx, engine.Cmd{Engine: "hb-subset", Args: []string{"--unicodes=" + unicodes, "--output-file=" + src, f.file},
				Inputs: []string{f.file}, Outputs: []string{src}}); err != nil {
				return cli.Fail(stderr, "fonts", err)
			}
		}
		data, err := os.ReadFile(src)
		if err != nil {
			return cli.Fail(stderr, "fonts", err)
		}
		fm := formats[strings.ToLower(filepath.Ext(f.file))]
		fmt.Fprintf(&b, "@font-face {\n  font-family: %q;\n  font-style: %s;\n  font-weight: %s;\n  font-display: %s;\n  src: url(data:%s;base64,%s) format(%q);\n}\n",
			f.family, f.style, f.weight, *display, fm[0], base64.StdEncoding.EncodeToString(data), fm[1])
	}
	if err := writeAtomic(*out, []byte(b.String())); err != nil {
		return cli.Fail(stderr, "fonts", err)
	}
	fmt.Fprintf(stdout, "wrote %s (%d faces, %d bytes)\n", *out, len(faces), b.Len())
	return 0
}

// writeAtomic writes data to a temporary file beside path and renames it
// into place, so path is never a partly written file.
func writeAtomic(path string, data []byte) error {
	f, err := os.CreateTemp(filepath.Dir(path), ".plate-fonts-")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	if _, err := f.Write(data); err != nil {
		f.Close()
		return err
	}
	if err := f.Chmod(0o644); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(f.Name(), path)
}
